<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
	  <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	  <Nullable>disable</Nullable>
	  <ImplicitUsings>disable</ImplicitUsings>
	  <DefaultItemExcludes>$(DefaultItemExcludes);CerberusInstaller\**;artifacts\**;Tests\**</DefaultItemExcludes>
  </PropertyGroup>
  <ItemGroup>
	  <Compile Remove="Install\**" />
	  <Compile Remove="publish\**" />
	  <Content Remove="Install\**" />
	  <Content Remove="publish\**" />
	  <EmbeddedResource Remove="Install\**" />
	  <EmbeddedResource Remove="publish\**" />
	  <None Remove="Install\**" />
	  <None Remove="publish\**" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Tests\CerberusDashboard.RegressionTests\CerberusDashboard.RegressionTests.csproj" />
    <None Include="Tests\CerberusDashboard.RegressionTests\README.md" />
  </ItemGroup>
  <ItemGroup Condition="'$(CerberusInstallerBuild)' == 'true'">
	  <Content Update="appsettings*.json" CopyToPublishDirectory="Never" />
  </ItemGroup>
  <ItemGroup>
	  <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.0" />
	  <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson" Version="10.0.0" />
	  <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
	  <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
</Project>
